### ISSUE TITLE
DiscussionPolicy::find breaks with other extensions

### ISSUE THREAD

**Issue by clarkwinkelmann** [askvortsov1/flarum-help-tags#1]
I have found some issues when your extension is used together with my premium Wordpress extension.

In my code, I do

    Discussion::where('kilowhat_wordpress_post_id', $id)->whereVisibleTo($user)->firstOrFail();

But instead of returning the post that has the given `kilowhat_wordpress_post_id`, it always returns the first discussion of the database.

The issue is because your extension adds an `->orWhere()` to the query that I'm building, making it in-operational.

The issue is in the `find` method here https://github.com/askvortsov1/flarum-help-tags/blob/master/src/Access/DiscussionPolicy.php

I believe line 46 is a special test to detect when Flarum performs `Discussion::where('id', $id)->whereVisibleTo($user)`, so it will work there, but not work for third-party extensions that make custom requests from the Discussion model.

I'm not sure what the best solution is, and I have some trouble understanding what exactly your code in `find` does. It looks over-complicated.

**Comment by askvortsov1** [comment]
Essentially, the code in find should insert a check that will always allow a user to see discussions where they are the author. However, if that orWhere is followed by an andWhere, the effect is essentially nullified, so I set up this annoyingly convoluted system to always insert the orWhere at the start of the query. Unfortunately, this has the unintended (and previously unconsidered) side effect of nullifying any where clauses that might be added to a query that uses whereVisibleTo. 

Essentially, the ideal situation would be if this:
`// Hide discussions which have tags that the user is not allowed to see.
        $query->whereNotIn('discussions.id', function ($query) use ($actor) {
            return $query->select('discussion_id')
                ->from('discussion_tag')
                ->whereIn('tag_id', Tag::getIdsWhereCannot($actor, 'viewDiscussions'));
        });`
allowed discussion authors to see discussions they created, regardless of whether they had the viewDiscussions permission in that tag.
